### ISSUE TITLE
Got TypeError while training the model

### ISSUE THREAD

**Issue by shantanuo** [apoorvnandan/speech-recognition-primer#1]
The code works as expected till this line. But getting an error while training the model.

model = ASR(200, 11, 2, 'valid', 200, 29)

optimizer = tf.keras.optimizers.Adam()

train(model, optimizer, X, y, 100)

The error:

> TypeError                                 Traceback (most recent call last)
> <ipython-input-16-6fb50ec29a0d> in <module>
>       1 model = ASR(200, 11, 2, 'valid', 200, 29)
>       2 optimizer = tf.keras.optimizers.Adam()
> ----> 3 train(model, optimizer, X, y, 100)
> 
> <ipython-input-11-eee0d35ed4c1> in train(model, optimizer, X, Y, epochs)
>     145     '''
>     146     for step in range(1, epochs):
> --> 147         loss = train_sample(X, Y, optimizer, model)
>     148         print('Epoch {}, Loss: {}'.format(step, loss))
> 
> <ipython-input-11-eee0d35ed4c1> in train_sample(x, y, optimizer, model)
>     124         logits_length = [logits.shape[1]]*logits.shape[0]
>     125         labels_length = [labels.shape[1]]*labels.shape[0]
> --> 126         loss = compute_ctc_loss(logits, labels, logit_length=logits_length, label_length=labels_length)
>     127         loss = tf.reduce_mean(loss)
>     128     grads = tape.gradient(loss, model.trainable_variables)
> 
> <ipython-input-11-eee0d35ed4c1> in compute_ctc_loss(logits, labels, logit_length, label_length)
>      49         unique=None,
>      50         blank_index=-1,
> ---> 51         name=None
>      52     )
>      53 
> 
> TypeError: ctc_loss() got an unexpected keyword argument 'label_length'

**Comment by apoorvnandan** [comment]
Hi,

I think you are using Tensorflow 1.1x and not Tensorflow 2.0.
The function was changed in 2.0 and the new `tf.nn.ctc_loss` has an
argument `label_length`

Here are the docs for TF1.14 and TF2.0 for your reference.

https://www.tensorflow.org/api_docs/python/tf/nn/ctc_loss

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/nn/ctc_loss

**Comment by apoorvnandan** [comment]
Updated the Readme. Closing this issue.
